{% set data = load_setup_py_data() %}
{% set name = "plonk" %}

# Need to set version here, as opposed to reading from setup.py.
{% set version = "0.2.1" %}
# The sha256 hash corresponds to the source distribution from PyPI.
{% set sha256 = "c78416c177b8cf139436950a31a15087af84f17ec0d29621584722e36088a4a5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

extra:
  channels:
    - dmentipl

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
  run:
    - python
    - h5py
    - matplotlib
    - numba
    - numpy
    - pandas
    - pint
    - scikit-image>=0.16
    - scipy

about:
  home: {{ data["url"] }}
  license: {{ data["license"] }}
  summary: {{ data["description"] }}
